# syntax=docker/dockerfile:1.7

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["RollblackLegacy.Auth/", "RollblackLegacy.Auth/"]
COPY ["RollblackLegacy.Website/", "RollblackLegacy.Website/"]
COPY ["RollblackLegacy.Website.Application/", "RollblackLegacy.Website.Application/"]
COPY ["RollblackLegacy.Website.Infrastructure/", "RollblackLegacy.Website.Infrastructure/"]
COPY ["RollblackLegacy.Website.Contracts/", "RollblackLegacy.Website.Contracts/"]
COPY ["RollblackLegacy.Website.Domain/", "RollblackLegacy.Website.Domain/"]

WORKDIR /src/RollblackLegacy.Website
RUN dotnet restore "RollblackLegacy.Website.csproj"
RUN dotnet publish "RollblackLegacy.Website.csproj" -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish/ ./

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "RollblackLegacy.Website.dll"]
